print("Welcome to the Band Name Generator.")
city_name = input("What's the name of the city you grew up in?\n")
pet_name = input("What's your pet's name?\n")
print(pet_name)
print("Your Band name could be " + city_name + " " + pet_name)